name: build_app_dev

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  build:  # build only and deploy manually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Build and push image
        run: |
          cat .env
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u qnx-dev --password-stdin
          docker pull $IMAGE_TAG
          docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
          docker push $IMAGE_TAG
        env:
          IMAGE_TAG: ghcr.io/qnx-emergingtech/weatheringwithu:dev
